{
 "title": "Notification statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (notification_action) (delta(notification_statistics_by_alert_name_total{job=\"harp-daemon\"}[$__rate_interval]))",
     "legendFormat": "{{alert_name}}"
    }
   ]
  },
  {
   "title": "Top 10: Sum by alert name",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (alert_name) (delta(notification_statistics_by_alert_name_total{job=\"harp-daemon\"}[$__range])))",
     "legendFormat": "{{alert_name}}"
    }
   ]
  },
  {
   "title": "Top 10: Sum by label",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (label_name, label_value) (delta(notification_statistics_by_labels_total{job=\"harp-daemon\"}[$__range])))",
     "legendFormat": "{{label_name}}: {{label_value}}"
    }
   ]
  },
  {
   "title": "Top 10: Sum by source",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (source, ms) (delta(notification_statistics_by_labels_total{job=\"harp-daemon\"}[$__range])))",
     "legendFormat": "{{ms}}: {{source}}"
    }
   ]
  },
  {
   "title": "Top 10: Alert duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (alert_name) (delta(notification_statistics_alert_duration{job=\"harp-daemon\"}[$__range])))",
     "legendFormat": "{{alert_name}}"
    }
   ]
  },
  {
   "title": "Top 10: User actions",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, count by (event_name, user_name) (delta(notification_statistics_by_alert_name_total{service=\"harp-actions\"}[$__range])))",
     "legendFormat": "{{user_name}}: {{event_name}}"
    }
   ]
  },
  {
   "title": "Top 100: Alerts by label value",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, sum by (alert_name, label_name, label_value) (delta(notification_statistics_by_labels_total{job=\"harp-daemon\"}[$__range])))",
     "legendFormat": "{{alert_name}}"
    }
   ]
  },
  {
   "title": "Alerts per monitoring system",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (source, ms) (rate(notification_statistics_by_alert_name_total{job=\"harp-daemon\"}[$__rate_interval]) * 30)",
     "legendFormat": "{{ms}}: {{source}}"
    }
   ]
  },
  {
   "title": "Trend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (alert_name) (rate(notification_statistics_by_alert_name_total{job=\"harp-daemon\"}[$__rate_interval]) * 30)",
     "legendFormat": " {{alert_name}}"
    }
   ]
  }
 ]
}