{
 "title": "Status Page",
 "description": "Keep an eye on running services and missing processes.",
 "tags": [
  "collectd",
  "influxdb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Services",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "min by(service) (probe_success{service=~\".*.\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datastores",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "min by(datastore) (probe_success{datastore=~\".*.\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Group Max Lag Seconds",
   "type": "graph",
   "description": "Max extrapolated lag in seconds for each consumer group.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_max_lag_seconds{group!=\"\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 } },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "{severity=\"error\"} |= ``"
    }
   ]
  }
 ]
}