{
 "title": "Service: harp-licenses",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Flask Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests count  =! 200",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status!=\"200\", job=\"harp-licenses\"}[1m])",
     "legendFormat": "{{pod}}: {{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "GET: Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{method=\"GET\",status=\"200\", job=\"harp-licenses\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "GET: Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{method=\"GET\",status=\"200\", job=\"harp-licenses\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"GET\",status=\"200\", job=\"harp-licenses\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "POST: Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{method=\"POST\",status=\"200\", job=\"harp-licenses\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "POST: Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{method=\"POST\",status=\"200\", job=\"harp-licenses\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"POST\",status=\"200\", job=\"harp-licenses\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PUT: Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{method=\"PUT\",status=\"200\", job=\"harp-licenses\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PUT: Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{method=\"PUT\",status=\"200\", job=\"harp-licenses\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"PUT\",status=\"200\", job=\"harp-licenses\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "DELETE: Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{method=\"DELETE\",status=\"200\", job=\"harp-licenses\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "DELETE: Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{method=\"DELETE\",status=\"200\", job=\"harp-licenses\"}[1m]) /\nrate(flask_http_request_duration_seconds_count{method=\"DELETE\",status=\"200\", job=\"harp-licenses\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}