{
 "title": "Service: harp-daemon",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "General Service metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOTAL: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(total_notification_processor_latency_seconds_count{job=\"harp-daemon\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TOTAL: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(total_notification_processor_latency_seconds_sum{job=\"harp-daemon\"}[1m]) /\nrate(total_notification_processor_latency_seconds_count{job=\"harp-daemon\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "UI: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(ui_create_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(ui_update_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(ui_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(ui_close_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "UI: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ui_create_notification_latency_seconds_sum{job=\"harp-daemon\"}[1m])) /\nsum(rate(ui_create_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(ui_update_notification_latency_seconds_sum{job=\"harp-daemon\"}[1m])) /\nsum(rate(ui_update_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(ui_resubmit_notification_latency_seconds_sum{job=\"harp-daemon\"}[1m])) /\nsum(rate(ui_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(ui_close_notification_latency_seconds_sum{job=\"harp-daemon\"}[1m])) /\nsum(rate(ui_close_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "EMAIL: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(email_create_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(email_update_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(email_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(email_close_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "EMAIL: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(email_create_notification_latency_seconds_sum{job=\"harp-daemon\"}[1m])) /\nsum(rate(email_create_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(email_update_notification_latency_seconds_sum{job=\"harp-daemon\"}[1m])) /\nsum(rate(email_update_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(email_resubmit_notification_latency_seconds_sum{job=\"harp-daemon\"}[1m])) /\nsum(rate(email_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(email_close_notification_latency_seconds_sum{job=\"harp-daemon\"}[1m])) /\nsum(rate(email_close_notification_latency_seconds_count{job=\"harp-daemon\"}[1m]))",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "JIRA: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(jira_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(jira_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(jira_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(jira_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "JIRA: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jira_create_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(jira_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(jira_update_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(jira_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(jira_resubmit_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(jira_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(jira_close_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(jira_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "PD: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(pd_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(pd_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(pd_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(pd_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "PD: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(pd_create_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(pd_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(pd_update_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(pd_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(pd_resubmit_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(pd_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(pd_close_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(pd_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "SKYPE: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(skype_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(skype_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(skype_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(skype_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "SKYPE: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(skype_create_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(skype_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(skype_update_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(skype_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(skype_resubmit_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(skype_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(skype_close_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(skype_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "SMS: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(sms_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(sms_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(sms_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(sms_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "SMS: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(sms_create_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(sms_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(sms_update_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(sms_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(sms_resubmit_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(sms_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(sms_close_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(sms_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "TEAMS: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(teams_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(teams_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(teams_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(teams_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "TEAMS: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(teams_create_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(teams_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(teams_update_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(teams_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(teams_resubmit_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(teams_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(teams_close_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(teams_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "TELEGRAM: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(telegram_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(telegram_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(telegram_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(telegram_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "TELEGRAM: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(telegram_create_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(telegram_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(telegram_update_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(telegram_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(telegram_resubmit_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(telegram_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(telegram_close_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(telegram_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "VOICE: Notifications count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(voice_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(voice_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(voice_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(voice_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "VOICE: Notifications latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(voice_create_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(voice_create_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(voice_update_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(voice_update_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Update"
    },
    {
     "expr": "sum(rate(voice_resubmit_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(voice_resubmit_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Resubmit"
    },
    {
     "expr": "sum(rate(voice_close_notification_latency_seconds_sum{job=\"harp-daemon\"}[$Interval])) * 60 /\nsum(rate(voice_close_notification_latency_seconds_count{job=\"harp-daemon\"}[$Interval])) * 60",
     "legendFormat": "Close"
    }
   ]
  },
  {
   "title": "Notification Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ALERT_RESUBMIT_PROCESSOR_COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(alert_resubmit_processor_latency_seconds_count{job=\"harp-daemon\"}[$Interval]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ALERT_RESUBMIT_PROCESSOR_LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(alert_resubmit_processor_latency_seconds_sum{job=\"harp-daemon\"}[$Interval]) * 60 /\nrate(alert_resubmit_processor_latency_seconds_count{job=\"harp-daemon\"}[$Interval]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GRAPH_RENDER_PROCESSOR_COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(graph_render_processor_latency_seconds_count{job=\"harp-daemon\"}[$Interval]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GRAPH_RENDER_PROCESSOR_LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(graph_render_processor_latency_seconds_sum{job=\"harp-daemon\"}[$Interval]) * 60 /\nrate(graph_render_processor_latency_seconds_count{job=\"harp-daemon\"}[$Interval]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ALERT_ASSIGN_PROCESSOR_COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(alert_assign_processor_latency_seconds_count{job=\"harp-daemon\"}[$Interval]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ALERT_ASSIGN_PROCESSOR_LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(alert_assign_processor_latency_seconds_sum{job=\"harp-daemon\"}[$Interval]) * 60 /\nrate(alert_assign_processor_latency_seconds_count{job=\"harp-daemon\"}[$Interval]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ENV_DICT_UPDATE_PROCESSOR_COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(env_dict_update_processor_latency_seconds_count{job=\"harp-daemon\"}[$Interval]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ENV_DICT_UPDATE_PROCESSOR_LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(env_dict_update_processor_latency_seconds_sum{job=\"harp-daemon\"}[$Interval]) * 60 /\nrate(env_dict_update_processor_latency_seconds_count{job=\"harp-daemon\"}[$Interval]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}