{
 "title": "Service: harp-aggregator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "update_aerospike_cache_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(update_aerospike_cache_latency_seconds_count{job=\"harp-aggregator\"}[1m]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "update_aerospike_cache_latency_seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(update_aerospike_cache_latency_seconds_sum{job=\"harp-aggregator\"}[1m]) / rate(update_aerospike_cache_latency_seconds_count{job=\"harp-aggregator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "collect_active_alerts_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(collect_active_alerts_latency_seconds_count{job=\"harp-aggregator\"}[1m]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "collect_active_alerts_latency_seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(collect_active_alerts_latency_seconds_sum{job=\"harp-aggregator\"}[1m]) / rate(collect_active_alerts_latency_seconds_count{job=\"harp-aggregator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "aerospike_write_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(aerospike_write_latency_seconds_count{job=\"harp-aggregator\"}[1m]) * 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "aerospike_write_latency_seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aerospike_write_latency_seconds_sum{job=\"harp-aggregator\"}[1m]) / rate(aerospike_write_latency_seconds_count{job=\"harp-aggregator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}