{
 "title": "Service: harp-bridge",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Service metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Aerospike read count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "idelta(aerospike_read_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Aerospike read latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aerospike_read_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(aerospike_read_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client connect count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "idelta(client_connect_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client connect latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(client_connect_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(client_connect_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client disconnect count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "idelta(client_disconnect_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client disconnect latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(client_disconnect_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(client_disconnect_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client update_filter count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "idelta(client_update_filter_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client update_filter latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(client_update_filter_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(client_update_filter_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client update_room count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "idelta(client_update_room_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client update_room latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(client_update_room_latency_seconds_sum{job=\"harp-bridge\"}[1m]) /\nrate(client_update_room_latency_seconds_count{job=\"harp-bridge\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}