{
 "title": "Service: harp-alert-decorator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOTAL: Decorations count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(total_decorator_latency_seconds_count{job=\"harp-alert-decorator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TOTAL: Decoration latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(total_decorator_latency_seconds_sum{job=\"harp-alert-decorator\"}[1m]) /\nrate(total_decorator_latency_seconds_count{job=\"harp-alert-decorator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Environment: Decorations count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(environment_decorator_latency_seconds_count{job=\"harp-alert-decorator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Environment: Decoration latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(environment_decorator_latency_seconds_sum{job=\"harp-alert-decorator\"}[1m]) /\nrate(environment_decorator_latency_seconds_count{job=\"harp-alert-decorator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scenario: Decorations count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(scenario_decorator_latency_seconds_count{job=\"harp-alert-decorator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scenario: Decoration latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(scenario_decorator_latency_seconds_sum{job=\"harp-alert-decorator\"}[1m]) /\nrate(scenario_decorator_latency_seconds_count{job=\"harp-alert-decorator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Integration: Decorations count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(integration_decorator_latency_seconds_count{job=\"harp-alert-decorator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Integration: Decoration latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(integration_decorator_latency_seconds_sum{job=\"harp-alert-decorator\"}[1m]) /\nrate(integration_decorator_latency_seconds_count{job=\"harp-alert-decorator\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}